on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string
            push:
                required: true
                type: boolean
            context:
                required: false
                type: string
                default: .
            build_args:
                required: false
                type: string
            platforms:
                required: false
                type: string
                default: linux/amd64,linux/arm64,linux/arm/v7
            file:
                required: false
                type: string
                default: Dockerfile
            
        secrets:
            DOCKER_USERNAME:
                required: true
            DOCKER_PASSWORD:
                required: true
            GH_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@master
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@master
    
        - name: Login to DockerHub
          uses: docker/login-action@master
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: Login to GitHub Container Registry
          uses: docker/login-action@master
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GH_TOKEN }}
    
        - name: Build and push Docker images
          uses: docker/build-push-action@master
          with:
            context: ${{ inputs.context }}
            platforms: ${{ inputs.platforms }}
            build-args: ${{ inputs.build_args }}
            file: ${{ inputs.file }}
            push: ${{ inputs.push }}
            tags: ${{ inputs.tag }}